### ISSUE TITLE
How can we pass an arguments in extension?

### ISSUE THREAD

**Issue by antick** [bitpressio/blade-extensions#1]
How can we pass an argument? Can anyone show an example?

**Comment by paulredmond** [comment]
Hey @pankajsanam 👋 

Do you mean an argument to a blade directive? Or an extension class?

If you mean the former, check the Laravel documentation on [extending Blade](https://laravel.com/docs/5.7/blade#extending-blade).

If you mean a blade extension class' constructor arguments that you will register with this package, the extension classes are registered in Laravel's service container and tagged as a blade extension. This package gets all services tagged and registers them with Blade for you.

You can inject other services that your extensions depend upon, and pass any custom arguments that you want to the constructor:

```php

use \App\Blade\CartExtension::class;
use BitPress\BladeExtension\Container\BladeRegistrar;

BladeRegistrar::register(CartExtension::class, function () {
    // Do stuff...

    return new CartExtension($stuff);
});
```

**Comment by antick** [comment]
Hi @paulredmond 

First of all, thanks a ton for creating this cool package and responding to my problem.

I am trying to pass an argument in my blade directive. I am calling a directive which accepts an argument as Eloquent object. For example-
```php
@pagination($userModel)
```

In the laravel approach, I would have done something like this to achieve the above-

```php
Blade::directive('pagination', function ($model = null) {
    if ($model) {
        return "<?php echo view('partial.pagination', ['model' => $model])->render(); ?>";
    }
});
```

But I am not sure how to do the same with this package. I tried to add the parameter like this in my Blade extension class

```php
public function pagination($model)
{
    return view('my.partial', ['model' => $model])->render();
}
```

But above does not work and considers the parameter as a string. Can you help with this? How can I pass an argument in Blade directive through your package?

Thank you.

**Comment by paulredmond** [comment]
@pankajsanam if I read your issue correctly, the directives defined in a class that this package registers still need to return the PHP version instead of returning directly. This package is just a lightweight structure around registering blade extensions in one class and allows you to inject services you might need from the service container. Does that make sense?

**Comment by paulredmond** [comment]
In other words, it will look just like any other `Blade::directive()` call, just that you can auto-register them all through tags and combine directives in one class.

The real benefit of this package is probably related app directives in one class and the ability to inject services since all of the extensions are registered in the container.
